export const UserData = [
  {
    first_name: "Mathew",
    last_name: "Maxwell",
    email: "stephanie19@example.net",
    trx_id: 10238475,
    user_status: "Active",
    last_seen: "20/09/2022",
    payment_status: "Overdue",
    payment_date: "No data",
    due_date: "24/12/2021",
    amount: 7474,
    currency: "USD",
    symbol: "$",
    user_activity: [
      {
        date: "20/06/2021",
        activity: "Made a Purchase Order",
        details:
          "The User made a Purchase Order for 5 Goods and Payed via Card. The User also Paid for delivery via Courier services",
      },
      {
        date: "10/02/2021",
        activity: "Checked Price of Goods",
        details:
          "The user navigated to the Pricing page of 'Anti-blue Reflection Glass' and checked the price of the Goods",
      },
      {
        date: "2/02/2021",
        activity: "User cancelled Order",
        details:
          "User requested Cancellation of Order on 3 goods citing reasons that 'Payment Gateway not responding",
      },
    ],
  },
  {
    first_name: "Mark",
    last_name: "Dixon",
    email: "jbrown@example.net",
    trx_id: 10983475,
    user_status: "Active",
    last_seen: "20/09/2022",
    payment_status: "Unpaid",
    payment_date: "12/12/2021",
    due_date: "24/12/2021",
    amount: 2123,
    currency: "USD",
    symbol: "$",
    user_activity: [
      {
        date: "12/02/2021",
        activity: "Made a Sales Order",
        details:
          "The User made a Purchase Order for 5 Goods and Payed via Card. The User also Paid for delivery via Courier services",
      },
      {
        date: "10/02/2021",
        activity: "Checked Price of Services",
        details:
          "The user navigated to the Pricing page of 'Anti-blue Reflection Glass' and checked the price of the Goods",
      },
      {
        date: "2/02/2021",
        activity: "User cancelled Order",
        details:
          "User requested Cancellation of Order on 3 goods citing reasons that 'Payment Gateway not responding",
      },
    ],
  },
  {
    first_name: "Obinna",
    last_name: "Dick",
    email: "obinnadick@example.net",
    trx_id: 10983475,
    user_status: "Active",
    last_seen: "20/09/2022",
    payment_status: "Unpaid",
    payment_date: "12/12/2021",
    due_date: "24/12/2021",
    amount: 2123,
    currency: "USD",
    symbol: "$",
    user_activity: [
      {
        date: "12/02/2021",
        activity: "Made a Sales Order",
        details:
          "The User made a Purchase Order for 5 Goods and Payed via Card. The User also Paid for delivery via Courier services",
      },
      {
        date: "10/02/2021",
        activity: "Checked Price of Services",
        details:
          "The user navigated to the Pricing page of 'Anti-blue Reflection Glass' and checked the price of the Goods",
      },
      {
        date: "2/02/2021",
        activity: "User cancelled Order",
        details:
          "User requested Cancellation of Order on 3 goods citing reasons that 'Payment Gateway not responding",
      },
    ],
  },
  {
    first_name: "Joy",
    last_name: "Jane",
    email: "joyjane@example.net",
    trx_id: 10983475,
    user_status: "Active",
    last_seen: "20/09/2022",
    payment_status: "Unpaid",
    payment_date: "12/12/2021",
    due_date: "24/12/2021",
    amount: 2123,
    currency: "USD",
    symbol: "$",
    user_activity: [
      {
        date: "12/02/2021",
        activity: "Made a Sales Order",
        details:
          "The User made a Purchase Order for 5 Goods and Payed via Card. The User also Paid for delivery via Courier services",
      },
      {
        date: "10/02/2021",
        activity: "Checked Price of Services",
        details:
          "The user navigated to the Pricing page of 'Anti-blue Reflection Glass' and checked the price of the Goods",
      },
      {
        date: "2/02/2021",
        activity: "User cancelled Order",
        details:
          "User requested Cancellation of Order on 3 goods citing reasons that 'Payment Gateway not responding",
      },
    ],
  },
  {
    first_name: "Joseph",
    last_name: "Weaver",
    email: "sarahmiranda@example.net",
    trx_id: 10486475,
    user_status: "Active",
    last_seen: "20/09/2022",
    payment_date: "No data",
    payment_status: "Unpaid",
    due_date: "24/12/2021",
    amount: 300,
    currency: "USD",
    symbol: "$",
    user_activity: [],
  },
  {
    first_name: "Amanda",
    last_name: "Meyer",
    email: "emilyrobinson@example.net",
    trx_id: 10232195,
    user_status: "Active",
    last_seen: "20/09/2022",
    payment_status: "Paid",
    payment_date: "12/12/2021",
    due_date: "24/12/2021",
    amount: 8448,
    currency: "USD",
    symbol: "$",
    user_activity: [],
  },
  {
    first_name: "Michelle",
    last_name: "Jones",
    email: "evansricardo@example.org",
    trx_id: 10238475,
    user_status: "Active",
    last_seen: "20/09/2022",
    payment_status: "Overdue",
    payment_date: "12/12/2021",
    due_date: "24/12/2021",
    amount: 7494,
    currency: "USD",
    symbol: "$",
    user_activity: [
      {
        date: "12/02/2021",
        activity: "Made a Purchase Order",
        details:
          "The User made a Purchase Order for 5 Goods and Payed via Card. The User also Paid for delivery via Courier services",
      },
      {
        date: "10/02/2021",
        activity: "Checked Price of Goods",
        details:
          "The user navigated to the Pricing page of 'Anti-blue Reflection Glass' and checked the price of the Goods",
      },
      {
        date: "2/02/2021",
        activity: "User cancelled Order",
        details:
          "User requested Cancellation of Order on 3 goods citing reasons that 'Payment Gateway not responding",
      },
    ],
  },
  {
    first_name: "Sherry",
    last_name: "Hawkins",
    email: "sandra38@example.com",
    trx_id: 10983475,
    user_status: "Active",
    last_seen: "20/09/2022",
    payment_status: "Paid",
    payment_date: "12/12/2021",
    due_date: "24/12/2021",
    amount: 4094,
    currency: "USD",
    symbol: "$",
    user_activity: [
      {
        date: "12/02/2021",
        activity: "Made a Sales Order",
        details:
          "The User made a Purchase Order for 5 Goods and Payed via Card. The User also Paid for delivery via Courier services",
      },
      {
        date: "10/02/2021",
        activity: "Checked Price of Services",
        details:
          "The user navigated to the Pricing page of 'Anti-blue Reflection Glass' and checked the price of the Goods",
      },
      {
        date: "2/02/2021",
        activity: "User cancelled Order",
        details:
          "User requested Cancellation of Order on 3 goods citing reasons that 'Payment Gateway not responding",
      },
    ],
  },
  {
    first_name: "Maria",
    last_name: "Campos",
    email: "kburgess@example.com",
    trx_id: 10486475,
    user_status: "Active",
    last_seen: "20/09/2022",
    payment_date: "12/12/2021",
    payment_status: "Paid",
    due_date: "24/12/2021",
    amount: 4660,
    currency: "USD",
    symbol: "$",
    user_activity: [],
  },
  {
    first_name: "William",
    last_name: "Lowe",
    email: "guerraapril@example.com",
    trx_id: 10232195,
    user_status: "Active",
    last_seen: "20/09/2022",
    payment_status: "Paid",
    payment_date: "12/12/2021",
    due_date: "24/12/2021",
    amount: 5365,
    currency: "USD",
    symbol: "$",
    user_activity: [],
  },
  {
    first_name: "Tyler",
    last_name: "Hudson",
    email: "ruizangel@example.net",
    trx_id: 10238475,
    user_status: "Active",
    last_seen: "20/09/2022",
    payment_status: "Paid",
    payment_date: "12/12/2021",
    due_date: "24/12/2021",
    amount: 1328,
    currency: "USD",
    symbol: "$",
    user_activity: [
      {
        date: "12/02/2021",
        activity: "Made a Purchase Order",
        details:
          "The User made a Purchase Order for 5 Goods and Payed via Card. The User also Paid for delivery via Courier services",
      },
      {
        date: "10/02/2021",
        activity: "Checked Price of Goods",
        details:
          "The user navigated to the Pricing page of 'Anti-blue Reflection Glass' and checked the price of the Goods",
      },
      {
        date: "2/02/2021",
        activity: "User cancelled Order",
        details:
          "User requested Cancellation of Order on 3 goods citing reasons that 'Payment Gateway not responding",
      },
    ],
  },
  {
    first_name: "Sandra",
    last_name: "Chaves",
    email: "george70@example.org",
    trx_id: 10983475,
    user_status: "Active",
    last_seen: "20/09/2022",
    payment_status: "Unpaid",
    payment_date: "12/12/2021",
    due_date: "24/12/2021",
    amount: 5627,
    currency: "USD",
    symbol: "$",
    user_activity: [
      {
        date: "12/02/2021",
        activity: "Made a Sales Order",
        details:
          "The User made a Purchase Order for 5 Goods and Payed via Card. The User also Paid for delivery via Courier services",
      },
      {
        date: "10/02/2021",
        activity: "Checked Price of Services",
        details:
          "The user navigated to the Pricing page of 'Anti-blue Reflection Glass' and checked the price of the Goods",
      },
      {
        date: "2/02/2021",
        activity: "User cancelled Order",
        details:
          "User requested Cancellation of Order on 3 goods citing reasons that 'Payment Gateway not responding",
      },
    ],
  },
  {
    first_name: "Jessica",
    last_name: "Taylor",
    email: "emily66@example.net",
    trx_id: 10486475,
    user_status: "Active",
    last_seen: "20/09/2022",
    payment_date: "12/12/2021",
    payment_status: "Unpaid",
    due_date: "24/12/2021",
    amount: 9574,
    currency: "USD",
    symbol: "$",
    user_activity: [],
  },
  {
    first_name: "Kathy",
    last_name: "Torres",
    email: "brittany39@example.com",
    trx_id: 10232195,
    user_status: "Active",
    last_seen: "20/09/2022",
    payment_status: "Unpaid",
    payment_date: "12/12/2021",
    due_date: "24/12/2021",
    amount: 2608,
    currency: "USD",
    symbol: "$",
    user_activity: [],
  },
  {
    first_name: "Lisa",
    last_name: "Clark",
    email: "waltonstephen@example.com",
    trx_id: 10238475,
    user_status: "Active",
    last_seen: "20/09/2022",
    payment_status: "Paid",
    payment_date: "12/12/2021",
    due_date: "24/12/2021",
    amount: 8626,
    currency: "USD",
    symbol: "$",
    user_activity: [
      {
        date: "12/02/2021",
        activity: "Made a Purchase Order",
        details:
          "The User made a Purchase Order for 5 Goods and Payed via Card. The User also Paid for delivery via Courier services",
      },
      {
        date: "10/02/2021",
        activity: "Checked Price of Goods",
        details:
          "The user navigated to the Pricing page of 'Anti-blue Reflection Glass' and checked the price of the Goods",
      },
      {
        date: "2/02/2021",
        activity: "User cancelled Order",
        details:
          "User requested Cancellation of Order on 3 goods citing reasons that 'Payment Gateway not responding",
      },
    ],
  },
  {
    first_name: "Alisson",
    last_name: "Johnson",
    email: "alanjackson@example.org",
    trx_id: 10983475,
    user_status: "Inactive",
    last_seen: "20/09/2022",
    payment_status: "Unpaid",
    payment_date: "12/12/2021",
    due_date: "24/12/2021",
    amount: 5024,
    currency: "USD",
    symbol: "$",
    user_activity: [
      {
        date: "12/02/2021",
        activity: "Made a Sales Order",
        details:
          "The User made a Purchase Order for 5 Goods and Payed via Card. The User also Paid for delivery via Courier services",
      },
      {
        date: "10/02/2021",
        activity: "Checked Price of Services",
        details:
          "The user navigated to the Pricing page of 'Anti-blue Reflection Glass' and checked the price of the Goods",
      },
      {
        date: "2/02/2021",
        activity: "User cancelled Order",
        details:
          "User requested Cancellation of Order on 3 goods citing reasons that 'Payment Gateway not responding",
      },
    ],
  },
  {
    first_name: "Micheal",
    last_name: "Harris",
    email: "angelataylor@example.net",
    trx_id: 10486475,
    user_status: "Active",
    last_seen: "20/09/2022",
    payment_date: "12/12/2021",
    payment_status: "Unpaid",
    due_date: "24/12/2021",
    amount: 3280,
    currency: "USD",
    symbol: "$",
    user_activity: [],
  },
  {
    first_name: "Katherine",
    last_name: "Smith",
    email: "chaveztammy@example.net",
    trx_id: 10232195,
    user_status: "Active",
    last_seen: "20/09/2022",
    payment_status: "Paid",
    payment_date: "12/12/2021",
    due_date: "24/12/2021",
    amount: 4314,
    currency: "USD",
    symbol: "$",
    user_activity: [],
  },
];